# YOUR NAME OR TITLE OF YOUR SITE
name: Davi Santiago

# YOUR BRAND/PERSONAL TAGLINE
tagline: Mussum Ipsum, cacilds vidis litro abertis. Suco de cevadiss deixa as pessoas mais interessantis.Sapien in monti palavris qui num significa nadis i pareci latim.Cevadis im ampola pa arma uma pindureta.Si u mundo tá muito paradis? Toma um mé que o mundo vai girarzis!

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/davixsan.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # GITHUB
  - Name: GitHub
    URL: http://github.com
    Username: davixsan
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # GITHUB
  - Name: GitHub
    URL: https://vanessabcs.github.io
    Username: 
    Color: '#6e5494'
    Icon-Class: fab fa-github

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: 
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # Cal.com
 

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
