# YOUR NAME OR TITLE OF YOUR SITE
name: Davi Santiago

# YOUR BRAND/PERSONAL TAGLINE
tagline: Relaxa que isso é uma simulação.

# YOUR/BRAND IMAGE URL
Image_URL: https://github.com/davixsan.png

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK
    
    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: harsh98trivedi
    Color: '#3b5998'
    Icon-Class: fab fa-github

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: harsh98trivedi
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram

    # TWITTER
  - Name: Twitter
    URL: https://twitter.com
    Username: harsh98trivedi
    Color: '#1DA1F2'
    Icon-Class: fab fa-twitter

    # Cal.com
 

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: ''

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
# baseurl: /links

# Default Markdown Engine
markdown: kramdown
